[profile.default]
libs = ["lib"]
out = "out"
remappings = ['@chainlink/contracts/src/v0.8/vrf/=lib/chainlink-brownie-contracts/contracts/src/v0.8/', 'forge-std/=lib/forge-std/src/']

src = "src"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
