[profile.default]
libs = ["lib"]
out = "out"
# remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/']
remappings = ['@chainlink/contracts/src/v0.8/vrf/=lib/chainlink-brownie-contracts/contracts/src/v0.8/']

src = "src"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
